### ISSUE TITLE
Per world chat feature

### ISSUE THREAD

**Issue by Runkang10** [omardotcontent/WorldChatter#2]
**Is your feature request related to a problem? Please describe.**
Add per world chat feature since many plugins that offer this feature are all outdated.

**Describe the solution you'd like**
Per world chat with a feature to put into groups for example:
```YAML
groups:
  - group1:
    - world
    - world_nether
    - world_the_end
  - group2:
    - lobby
    - bedwards_lobby
```
